### ISSUE TITLE
Move proposal

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/Top_Predictors_for_Great_Wine#37]
At this point, I would recommend moving the proposal out of the README and into a document named something like `proposal.md` in the docs. Or delete it (it lives on in the history). It doesn't really fit in the README at this late stage in the project.

On a related note, I'd add some key findings to your overview (1-2 sentences) and a link to the rendered final report in the README.

**Comment by ttimbers** [comment]
However, I would keep a link to where the data came from in a visible place in the README.

**Comment by ttimbers** [comment]
Also, the data was originally licensed under the ShareAlike license, so you'll need to include that in your repo too... https://creativecommons.org/licenses/by-nc-sa/4.0/

**Comment by aylapear** [comment]
The proposal as been removed from the readme. It can be found in prior committed versions. A ShareAlike licence file has been added and did double checked and fixed up references to the data set.
