### ISSUE TITLE
targets in Makefile should be files

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/Top_Predictors_for_Great_Wine#38]
Three of the targets in your Makefile are directories, they should be the files. If you don't do this, it's harder to identify/fix bugs that affect a certain file. Also, it's not clear to the reader what the dependencies are.

**Comment by ttimbers** [comment]
The three I am referring to are: `results/viz_`, `results/model_`, `results/results_`. And let me be clear, that you do not need to change the Python script at all just the target, for example, for `results/viz_` I think it should look something like this:

```
results/viz_countries.png results/viz_class_frequencies.png results/viz_price_boxplot.png results/viz_price_less_than_100_hist.png results/viz_variety.png : data/wine_data_cleaned.csv src/explore_data.py
	python src/explore_data.py data/wine_data_cleaned.csv results/viz_
```

**Comment by aylapear** [comment]
All dependencies have been added to the makefile scripts. including all the new csv's files that were created so that our tables aren't hard coded into the report.
