### ISSUE TITLE
Text in some visualizations is too small to read

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/Top_Predictors_for_Great_Wine#40]
Figure 4: Text in decision tree graphic is far to small to be useful. Could simplify if by rotating it 90 degrees (more room for bigger text!) and including less info on the graphic (value, samples and gini could be in a table in an appendix).

Figure 5: x-axis labels are pretty small... Stacking the plots vertically could help, and/or also rotating them 90 degrees.

**Comment by aylapear** [comment]
The decision tree graphic was rotated and which allowed it to increase in size.

**Comment by aylapear** [comment]
I believe this comment is referring to figure 7. The plots orientation has been changed and the text size increased.
